name: Build and Test New Website

on:
    pull_request:
        branches:
            - new-site-dev

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js from .nvmrc
              uses: actions/setup-node@v2
              with:
                  node-version-file: '.nvmrc'

            - name: Build website
              run: ./scripts/build-site.sh

            - name: Run tests
              run: yarn test
